apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: green
  name: nginx-t
  labels:
    app: nginx-t
spec:
  selector:
    matchLabels:
      app: nginx-t
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-t
        name: nginx-t
    spec:
      containers:
        - name: nginx-t
          image: nginx
          ports:
            - name: http
              containerPort: 80
              hostPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: green
  name: nginx-t-service
spec:
  selector:
    app: nginx-t
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80