apiVersion: v1
kind: Pod
metadata:
  name: green-blue
  namespace: green
spec:
  containers:
  - name: nginx-1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: keyvaluepair
    image: redis
    ports:
    - containerPort: 6379
  