apiVersion: v1
kind: Pod
metadata:
  name: green-blue
  namespace: green
spec:
  containers:
  - name: nginx-1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  containers:
  - name: nginx-2
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  containers:
  - name: nginx-3
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  containers:
  - name: nginx-4
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  containers:
  - name: nginx-5
    image: nginx:1.14.2
    ports:
    - containerPort: 80